# Generated by Django 4.2.6 on 2023-11-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_column='uuid', default=1379689523, max_length=16)),
                ('identifier', models.CharField(db_column='identifier', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uuid', models.CharField(db_column='uuid', default=2969058283, max_length=16, primary_key=True, serialize=False)),
                ('vehicle', models.ForeignKey(db_column='vehicles_uuid', on_delete=django.db.models.deletion.CASCADE, to='fleet_api.vehicle')),
            ],
        ),
    ]
