# Generated by Django 4.2.6 on 2023-11-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='uuid',
            field=models.CharField(db_column='uuid', default=470433377, max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='uuid',
            field=models.CharField(db_column='uuid', default=369248019, max_length=16),
        ),
    ]
